name: Sync labels to all repos

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/labels.yml'
      - '.github/workflows/sync-labels.yml'
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get all organization repositories
        id: get-repos
        run: |
          # Get all repos in the organization (adjust GITHUB_ORG if needed)
          GITHUB_ORG="${GITHUB_REPOSITORY_OWNER}"

          echo "Fetching repositories for organization: $GITHUB_ORG"

          # Fetch all repos (handles pagination)
          repos=$(gh api --paginate "/orgs/$GITHUB_ORG/repos" --jq '.[].name')

          if [ -z "$repos" ]; then
            echo "No repositories found or this might be a user account."
            # Try user repos instead
            repos=$(gh api --paginate "/user/repos" --jq '.[] | select(.owner.login == env.GITHUB_REPOSITORY_OWNER) | .name')
          fi

          echo "Found repositories:"
          echo "$repos"

          # Save to output
          echo "repos<<EOF" >> $GITHUB_OUTPUT
          echo "$repos" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.ORG_TOKEN }}

      - name: Sync labels to repositories
        run: |
          echo "Starting label sync process..."

          # Read the labels configuration
          if [ ! -f "labels.yml" ]; then
            echo "Error: labels.yml not found!"
            exit 1
          fi

          # Parse labels.yml using yq or pure bash
          # Install yq for easier YAML parsing
          wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod +x /usr/local/bin/yq

          GITHUB_ORG="${GITHUB_REPOSITORY_OWNER}"
          REPO_COUNT=0
          SUCCESS_COUNT=0
          FAIL_COUNT=0

          # Loop through each repository
          while IFS= read -r repo; do
            if [ -z "$repo" ]; then
              continue
            fi

            REPO_COUNT=$((REPO_COUNT + 1))
            echo ""
            echo "======================================"
            echo "Processing repository: $repo"
            echo "======================================"

            # Read each label from the YAML file
            label_count=$(yq eval '. | length' labels.yml)

            for ((i=0; i<$label_count; i++)); do
              name=$(yq eval ".[$i].name" labels.yml)
              color=$(yq eval ".[$i].color" labels.yml)
              description=$(yq eval ".[$i].description" labels.yml)

              # Remove quotes if present
              name=$(echo "$name" | tr -d '"')
              color=$(echo "$color" | tr -d '"')
              description=$(echo "$description" | tr -d '"')

              echo "  Syncing label: $name (color: $color)"

              # Check if label exists
              if gh api "/repos/$GITHUB_ORG/$repo/labels/$name" >/dev/null 2>&1; then
                echo "    Label exists, updating..."
                gh api --method PATCH "/repos/$GITHUB_ORG/$repo/labels/$name" \
                  -f new_name="$name" \
                  -f color="$color" \
                  -f description="$description" \
                  2>&1 || echo "    Warning: Failed to update label '$name'"
              else
                echo "    Label doesn't exist, creating..."
                gh api --method POST "/repos/$GITHUB_ORG/$repo/labels" \
                  -f name="$name" \
                  -f color="$color" \
                  -f description="$description" \
                  2>&1 || echo "    Warning: Failed to create label '$name'"
              fi
            done

            SUCCESS_COUNT=$((SUCCESS_COUNT + 1))
            echo "  ✓ Completed syncing labels for $repo"

          done <<< "${{ steps.get-repos.outputs.repos }}"

          echo ""
          echo "======================================"
          echo "Label Sync Summary"
          echo "======================================"
          echo "Total repositories processed: $REPO_COUNT"
          echo "Successful: $SUCCESS_COUNT"
          echo "Failed: $FAIL_COUNT"
          echo "======================================"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create summary
        if: always()
        run: |
          echo "## Label Sync Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Labels have been synced to all repositories" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Labels synced:**" >> $GITHUB_STEP_SUMMARY
          yq eval '.[] | "- " + .name + " (" + .color + ")"' labels.yml >> $GITHUB_STEP_SUMMARY
