name: Sync labels to all repos

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  list-repos:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.set.outputs.repos }}
    steps:
      - name: Get list of repos in organization
        id: fetch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_TOKEN }}
          script: |
            const org = context.repo.owner;
            const repos = await github.paginate(github.rest.repos.listForOrg, {
              org,
              type: "all",
              per_page: 100
            });

            const repoNames = repos
              .filter(r => !r.archived)
              .map(r => r.name);

            // Store in environment file
            require('fs').writeFileSync(
              process.env.GITHUB_OUTPUT,
              `repos=${JSON.stringify(repoNames)}\n`
            );
        id: set

  sync-labels:
    needs: list-repos
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.list-repos.outputs.repos) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync labels in ${{ matrix.repo }}
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.ORG_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: true
        env:
          GITHUB_REPOSITORY: ${{ github.repository_owner }}/${{ matrix.repo }}
