name: Sync labels to all repos

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get list of repos in organization
        id: repos
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_TOKEN }}
          script: |
            const org = context.repo.owner;
            const repos = await github.paginate(github.rest.repos.listForOrg, {
              org,
              type: "all",
              per_page: 100
            });
            return repos.map(r => r.name);

      - name: Sync labels across all repos
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          token: ${{ secrets.ORG_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: true
          repositories: ${{ steps.repos.outputs.result }}
